### ISSUE TITLE
New Vegas shows tiny square

### ISSUE THREAD

**Issue by dukenukemx** [iXit/wine-nine-standalone#93] opened 2020-12-28 06:52 UTC
When I start the game with Gallium Nine enabled I get this.  When I disable it then it doesn't happen.  Also, this can be fixed sometimes by switching between a different window open.  

![Screenshot from 2020-12-28 01-49-31](https://user-images.githubusercontent.com/31163475/103194958-3922f100-48af-11eb-8787-d68d2d47d9a1.png)

**Comment by axeldavy** [comment] 2021-01-08 21:56
Thanks for reporting this issue.
It seems regression, I played the game fine a few years ago.

**Comment by dhewg** [comment] 2021-02-07 07:28
Can you please paste a verbose debug log when this is happening?
`WINEDEBUG=d3d9nine wine ...`

What's window manager do you use?

**Comment by dhewg** [comment] 2021-02-07 14:37
Works for me, GOG v1.4, windowed as well as fullscreen in various resolutions and settings.
The initial window opens as small as on your screenshot, but it resized to the configured resolution moments later.

WINE v5.5 from debian and latest wine-nine-standalone on intel iris. Do you run older versions?

**Comment by dhewg** [comment] 2021-02-08 07:59
Also works with WINE v6.0 on radeon for me

**Comment by dhewg** [comment] 2021-03-27 09:32
There've been some related commits to the master branch, can you please test if your issue is fixed?

**Comment by dhewg** [comment] 2021-04-15 06:47
This should be fixed with current master or the upcoming v0.8.
If not please reopen this!

**Closed by dhewg** 2021-04-15 06:47 UTC
