### ISSUE TITLE
Poor performance on nouveau, same as not enabled

### ISSUE THREAD

**Issue by andysendo** [iXit/wine-nine-standalone#15] opened 2019-03-03 08:17 UTC
intel hd4600+nvidia k1100m,  wine4.0 + mesa18.2.8 + d3d9 nine standalone 0.3 present the same poor performance as not enabled. 

for example Trine 2: Complete Story, only got ~13 fps. i tried dri_prime or disable intel card login desktop got the same performance.  the output have any error or fixme messages about nine only activated etc.

compare to play the game with nvidia private driver got ~50 fps.

how to trace it? or nouveau is too bad no need to fix something.

regards.

**Comment by WuShichao** [comment] 2019-03-03 09:34
Same with me, AMD HD8670M, DRI_PRIME=1, same poor performance as not enabled, and no error.

**Comment by axeldavy** [comment] 2019-03-03 09:57
The first check is to verify Gallium Nine is used.
If the game is launched in a terminal it should show in green:
```
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9
```
wine ninewinecfg shows checks to see if everything can be loaded properly.

@andysendo It is difficult to pinpoint what could be your issue, but it's likely to be a nouveau issue. Lack of reclocking maybe ?
@WuShichao Are you sure gallium nine was activated ? Look at the checkbox in wine ninewinecfg

**Comment by WuShichao** [comment] 2019-03-03 10:41
@axeldavy I'm sure gallium nine was activated.

**Comment by andysendo** [comment] 2019-03-03 10:52
yes nine dll loaded.
is there any way to configure or trace nouveau module or nine?  
which dx9 game can tell nine could make performance much better than without it?

**Comment by axeldavy** [comment] 2019-03-03 11:19
@WuShichao With which game do you observe bad performance ?

@andysendo It depends. On my amd hd580 unigine heaven is 104.3fps on gallium nine and 78.2fps on wine, but would that be the same ratio on your card ? The gap between Gallium nine and wine used to be a lot greater years ago, but the opengl driver improved a lot since.

**Comment by axeldavy** [comment] 2019-03-03 11:32
@andysendo traces can be made with apitrace: 
https://github.com/iXit/wine-nine-standalone/wiki/apitrace
But these are usually not useful to find perf issues. It's more useful to debug visual issues.
Your perf gap 13fps -> 50fps is too big to be an inefficieny in gallium nine. The most likely explanation is a reclocking issue.

**Comment by andysendo** [comment] 2019-03-03 12:21
i5-4300m running the game cpu load > 230 by top command.
---> reclocking issue.
 so nouveau is bad for old k1100m, nine cant deal with it.

**Comment by WuShichao** [comment] 2019-03-04 09:16
@axeldavy All the games, same as nine turned off. But I remember it was fast enough when I run Windows 7 five years ago.

**Comment by WuShichao** [comment] 2019-03-04 11:44
@axeldavy Should I set DRI3?

**Comment by dhewg** [comment] 2019-03-05 09:41
It still sounds like gallium nine is not active for you guys. Can you please paste the output when launching some game?

**Comment by iiv3** [comment] 2019-03-15 23:12
Just a bit of info, k1100m seems to be a Kepler card and Nouveau lists it in [NVE0](https://nouveau.freedesktop.org/wiki/CodeNames/#NVE0) , the ["power management"](https://nouveau.freedesktop.org/wiki/PowerManagement/) lists `Engine recolocking` and `Memory reclocking` as "Work in Progress". So... it may be nouveau bug, but it might be easier to fix (compared to same problem with newer cards that are not supported at all).

At least on radeon the gpu clocks could be checked in `debugfs` ,  e.g. `cat /sys/kernel/debug/dri/0/*_pm_info`. See if you have these with nouveau and if they change under load.

Also, make sure you do have firmware and kernel modules loaded without errors. (e.g. `dmesg`)

Try few more applications. HalfLife2 Lost Coast should be free tech demo, Unigine has a number of benchmarks. Check if OpenGL games also have problems. e.g. "Xonotic" is free and native Quake3-like game you can try.
Actually can we see the output of `glxinfo -B` for the nvidia card?

**Comment by Saroufim** [comment] 2019-09-09 23:17
I'm having the same problem with nouveau. Here's the output of glxinfo -B:
`glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: nouveau (0x10de)
    Device: NVC1 (0xf02)
    Version: 19.2.0
    Accelerated: yes
    Video memory: 4090MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.3
    Max compat profile version: 4.3
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: nouveau
OpenGL renderer string: NVC1
OpenGL core profile version string: 4.3 (Core Profile) Mesa 19.2.0-rc1
OpenGL core profile shading language version string: 4.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.3 (Compatibility Profile) Mesa 19.2.0-rc1
OpenGL shading language version string: 4.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 19.2.0-rc1
`

**Comment by Venemo** [comment] 2019-09-10 08:40
@Saroufim Which hardware do you experience that problem on?

**Comment by Saroufim** [comment] 2019-09-10 08:45
Nvidia GeForce GT 730 detected by nouveau as NVIDIA GF108 (0c1100a1)

**Comment by dhewg** [comment] 2019-09-23 10:01
To summarize:
Different nvidia cards in use here, all using nouveau and the issue is most likely clocking issues
k1100m reclocking is 'WIP', 7200gt 'MOSTLY', whatever that means.
I don't see anything that we can fix, neither here, mesa or kernel.
It's nvidia that intentionally blocking the clocking issue

**Closed by dhewg** 2019-09-23 10:01 UTC
